FROM quay.io/centos/centos:stream9

ENV NAME=centos-stream-toolbox VERSION=9
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating CentOS toolbox containers" \
      maintainer="Mike Detwiler <mike@detwiler.io>"

RUN sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf
RUN dnf -y install dnf-plugins-core epel-release epel-next-release
RUN dnf -y config-manager --set-enabled crb

RUN dnf -y swap coreutils-single coreutils-full

COPY missing-docs /
RUN dnf -y reinstall $(<missing-docs)
RUN rm /missing-docs

COPY extra-packages /
RUN dnf -y install $(<extra-packages)
RUN rm /extra-packages

RUN dnf clean all
