#!/usr/bin/env bash

source /etc/os-release

case $VERSION_ID in
    18.04) clang=clang-10; clangd=clangd-10;;
    *) clang=clang; clangd=clangd;;
esac

export DEBIAN_FRONTEND=noninteractive
apt-get --assume-yes install \
    autoconf \
    automake \
    bash-completion \
    build-essential \
    can-utils \
    $clang \
    $clangd \
    clang-tidy \
    cmake \
    coreutils \
    cscope \
    curl \
    dos2unix \
    exuberant-ctags \
    file \
    gcovr \
    gpg \
    gzip \
    jq \
    libc++-dev \
    libc++abi-dev \
    libtool \
    minicom \
    python3-bottle \
    python3-certifi \
    python3-colorama \
    python3-coverage \
    python3-dateutil \
    python3-deprecation \
    python3-dev \
    python3-distro \
    python3-fasteners \
    python3-future \
    python3-jinja2 \
    python3-jwt \
    python3-nose \
    python3-pip \
    python3-pluginbase \
    python3-pygments \
    python3-requests \
    python3-setuptools \
    python3-six \
    python3-tabulate \
    python3-tqdm \
    python3-urllib3 \
    python3-wheel \
    python3-yaml \
    sharutils \
    software-properties-common \
    vim \
    wget \
    xxd
