#! /usr/bin/env bash

source /etc/os-release

case $VERSION_ID in
    8)
        epel_repo=powertools
        epel_release=epel-release
        epel_next_release=epel-next-release
        htop=htop
        pkgs_python='
        python3-certifi
        python3-colorama
        python3-coverage
        python3-dateutil
        python3-devel
        python3-distro
        python3-fasteners
        python3-future
        python3-jinja2
        python3-jwt
        python3-nose
        python3-pip
        python3-pygments
        python3-pyyaml
        python3-requests
        python3-setuptools
        python3-six
        python3-tabulate
        python3-tqdm
        python3-urllib3
        python3-wheel
        '
        ;;
    9)
        epel_repo=crb
        epel_release='https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-release-9-2.el9.noarch.rpm'
        epel_next_release='https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-next-release-9-2.el9.noarch.rpm'
        htop=''
        pkgs_python='
        python3-dateutil
        python3-devel
        python3-distro
        python3-jinja2
        python3-pip
        python3-pygments
        python3-pyyaml
        python3-requests
        python3-setuptools
        python3-six
        python3-tqdm
        python3-urllib3
        python3-wheel
        '
        ;;
esac

dnf --assumeyes config-manager --set-enabled $epel_repo

dnf --assumeyes install \
    $epel_release \
    $epel_next_release

dnf --assumeyes groupinstall \
    development \
    fedora-packager \
    rpm-development-tools

dnf --assumeyes install \
    bash-completion \
    bind-utils \
    clang-devel \
    clang-tools-extra \
    cmake \
    coreutils \
    cscope \
    curl \
    dos2unix \
    file \
    gnupg2 \
    gzip \
    $htop \
    jq \
    kernel-modules-extra \
    libpcap-devel \
    man-pages \
    minicom \
    nmap-ncat \
    sharutils \
    telnet \
    vim-enhanced \
    wget \
    zlib-devel

dnf --assumeyes install \
    $pkgs_python
