#! /usr/bin/env bash

set -euo pipefail

OS_RELEASE_FILE=${OS_RELEASE_FILE:-/etc/os-release}
source $OS_RELEASE_FILE

pkgs_common='
conan
'

case $ID in
    centos)
        pkgs_common="
        $pkgs_common
        black
        conan-package-tools
        "
        ;;
    fedora|ubuntu)
        pkgs_common="
        $pkgs_common
        conan-package-tools
        "
        ;;
esac

python3 -m pip install --upgrade $pkgs_common

case $ID in
    alpine)
        python3 -m pip install --upgrade --no-dependencies conan-package-tools
        ;;
    ubuntu)
        case $VERSION_ID in
            22.04)
                python3 -m pip cache purge
                ;;
        esac
        ;;
    *)
        python3 -m pip cache purge
        ;;
esac
