#! /usr/bin/env bash

set -euo pipefail

python3 -m pip install --upgrade \
    black \
    conan

python3 -m pip install --upgrade --no-dependencies \
    conan-package-tools

python3 -m pip cache purge || true
