FROM @CONTAINER_BASE_IMAGE@:@CONTAINER_BASE_TAG@

ENV NAME=@CONTAINER_NAME@ VERSION=@CONTAINER_TAG@

LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating @CONTAINER_DISTRO@ toolbox containers" \
      maintainer="@GIT_AUTHOR_NAME@ <@GIT_AUTHOR_EMAIL@>" \
      org.opencontainer.image.source="@PACKAGE_URL@" \
      org.opencontainer.image.url="@PACKAGE_URL@" \
      org.opencontainer.image.authors="@GIT_AUTHOR_NAME@ <@GIT_AUTHOR_EMAIL@>" \
      org.opencontainer.image.version="@PACKAGE_VERSION@"

ADD provision provision/
WORKDIR provision
RUN ./package-upgrade
RUN ./package-install
RUN ./pip-install
WORKDIR /
RUN rm -rf provision
