FROM @TOOLBOX_BASE_IMAGE@:@TOOLBOX_BASE_TAG@

ENV NAME=@TOOLBOX_NAME@ VERSION=@TOOLBOX_TAG@

LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating @TOOLBOX_DISTRO@ Toolbx containers" \
      maintainer="@GIT_AUTHOR_NAME@ <@GIT_AUTHOR_EMAIL@>" \
      org.opencontainer.image.source="@PACKAGE_URL@" \
      org.opencontainer.image.url="@PACKAGE_URL@" \
      org.opencontainer.image.authors="@GIT_AUTHOR_NAME@ <@GIT_AUTHOR_EMAIL@>" \
      org.opencontainer.image.version="@PACKAGE_VERSION@"

ADD provision provision/
WORKDIR provision
RUN ./package-upgrade-toolbox
RUN ./package-install-toolbox
RUN ./pip-install
WORKDIR /
RUN rm -rf provision
