#!/usr/bin/env bash

dnf -y upgrade
dnf -y groupinstall \
  c-development \
  development-tools \
  fedora-packager \
  headless-management \
  rpm-development-tools
dnf -y install \
  bash-completion \
  bind-utils \
  can-utils \
  clang-devel \
  gcovr \
  htop \
  jq \
  kernel-modules-extra \
  libcxx-devel \
  libcxxabi-devel \
  libpcap-devel \
  man-pages \
  nmap-ncat \
  python3-devel \
  python3-pip \
  telnet \
  vim-enhanced \
  zlib-devel
