#!/usr/bin/env bash

apk update
apk upgrade
apk add \
    autoconf \
    automake \
    alpine-sdk \
    bash-completion \
    cmake \
    coreutils \
    ctags \
    gcovr \
    gnupg \
    jq \
    libffi-dev \
    libtool \
    libxslt-dev \
    linux-headers \
    openssl-dev \
    py3-coverage \
    py3-nose \
    py3-pip \
    py3-setuptools \
    py3-wheel \
    python3-dev \
    rsync \
    vim
