#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive
apt-get -y remove libdvd-pkg lirc
apt-get -y update
apt-get -y upgrade
apt-get -y --install-suggests install \
  autoconf \
  automake \
  bash-completion \
  build-essential \
  can-utils \
  clang \
  clang-tidy \
  exuberant-ctags \
  jq \
  libtool \
  libc++-dev \
  libc++abi-dev \
  python3-dev \
  python3-pip \
  software-properties-common \
  vim
apt-get -y autoremove
