name: containers

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - base-image: quay.io/centos/centos
            base-tag: stream8
            distro: centos
          - base-image: quay.io/toolbx-images/centos-toolbox
            base-tag: stream9
            distro: centos
          - base-image: quay.io/toolbx-images/ubuntu-toolbox
            base-tag: 22.04
            distro: ubuntu
            #- base-image: registry.fedoraproject.org/fedora-toolbox
            #base-tag: 36
            #distro: fedora

    env:
      CONTAINER_BASE_IMAGE: ${{ matrix.base-image }}
      CONTAINER_BASE_TAG: ${{ matrix.base-tag }}
      CONTAINER_REGISTRY: "quay.io"
      CONTAINER_REPO: ${{ matrix.distro }}-toolbox
      GIT_AUTHOR_EMAIL: "mike@detwiler.io"
      GIT_AUTHOR_NAME: "Mike Detwiler"
      REGISTRY_ACCOUNT: "detwiler"
      USER: ${{ github.repository_owner }}

    steps:
      - name: Download Release Distribution Tarball
        id: dist-download
        uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "dev-box-*.tar.gz"

      - name: Configure Container Image Build
        run: |
          tar --transform='s|dev-box-[0-9.]*|dev-box|' -xzf dev-box-*.tar.gz
          cd dev-box
          ./configure
          make
          echo "PROJECT_VERSION=`cat .version`" >>$GITHUB_ENV

      - name: Build Container Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.CONTAINER_REPO }}
          tags: ${{ env.CONTAINER_BASE_TAG }} dev-box-${{ env.PROJECT_VERSION }}
          context: dev-box
          containerfiles: dev-box/Containerfile

      - name: Push Container Image
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.CONTAINER_REGISTRY }}/${{ env.REGISTRY_ACCOUNT }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Display Image URLs
        run: echo "${{ toJSON(steps.push-image.outputs) }}"
