name: containers

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - base-image: quay.io/centos/centos
            base-tag: stream8
            distro: centos
          - base-image: quay.io/centos/centos
            base-tag: stream9
            distro: centos
          - base-image: registry.fedoraproject.org/fedora-toolbox
            base-tag: 36
            distro: fedora
          - base-image: quay.io/toolbx-images/ubuntu-toolbox
            base-tag: 22.04
            distro: ubuntu

    env:
      CONTAINER_BASE_IMAGE: ${{ matrix.base-image }}
      CONTAINER_BASE_TAG: ${{ matrix.base-tag }}
      CONTAINER_REGISTRY: "quay.io"
      CONTAINER_REPO: ${{ matrix.distro }}-toolbox
      GIT_AUTHOR_EMAIL: "mike@detwiler.io"
      GIT_AUTHOR_NAME: "Mike Detwiler"
      REGISTRY_ACCOUNT: "detwiler"
      USER: ${{ github.repository_owner }}

    steps:
      - name: Download Release Distribution Tarball
        id: dist-download
        uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "dev-box-*.tar.gz"

      - name: Configure Container Build
        run: |
          echo tag_name ${{ steps.dist-download.outputs.tag_name }}
          version_tag=${{ steps.dist-download.outputs.tag_name }}
          version=${version_tag#v}
          ls -l
          tar -xzf dev-box-$version.tar.gz
          ls -l
          cd dev-box-$version
          ./configure
          make

      # steps below inspired by https://github.com/coreos/actions-lib/blob/main/build-container/action.yml
      - name: Build Container
        run: |
          version_tag=${{ steps.dist-download.outputs.tag_name }}
          version=${version_tag#v}
          podman manifest rm build 2>/dev/null ||:
          set -x
          podman build \
            --manifest build \
            --file dev-box-$version/Containerfile \
            dev-box-$version

      - name: Push container
        run: |
          mkdir -p ~/.docker
          cat > ~/.docker/config.json <<EOF
          ${{ secrets.QUAY_AUTH }}
          EOF
          podman manifest push build \
            $CONTAINER_REGISTRY/$REGISTRY_ACCOUNT/$CONTAINER_REPO:$CONTAINER_BASE_TAG

      - name: Remove credentials
        if: ${{ always() }}
        run: rm -f ~/.docker/config.json
